version: '3.8'

services:
  mysql:
    image: mysql:8.0  # Imagen oficial de MySQL 8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contraseña del root
      MYSQL_DATABASE: bancodb  # Nombre de la base de datos
    ports:
      - "3306:3306"
    networks:
      - backendNetwork
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d  # 🔥 Montamos la carpeta donde está BaseDatos.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/bancodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - backendNetwork
      - frontendNetwork
    volumes:
      - ./backend/target:/app/target 

  frontend:
    build:
      context: ./frontend
    container_name: angular_app
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - frontendNetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --port 4200

networks:
  backendNetwork:
  frontendNetwork:
